from typing import TypedDict, Any
from langgraph.graph import StateGraph, START, END
from agents import statistical_analyser, study_planer, study_validator, outcome_auditor

class MetaproteomicsAnylisisState(TypedDict): 
    data_raw_path: str #user input data
    study_plan: str | None # generated by agent 
    evaluation_study_plan: bool | None # Written by auditor, decide whether analysis should run
    downstream_analysis: bool | None # Written by analyzer, just check if it actually run
    data_outcomes: list[str] | None #written if data output 
    plot_paths:list[str] | None  #written if data output 
    issues: list[str] | None # written by all agents

# orchestration state decides which node runs nex

builder = StateGraph(MetaproteomicsAnylisisState)

# architecture of the graph 
builder.add_node("study design", study_planer)
builder.add_node("analyze and plot", statistical_analyser)
builder.add_node("studdy validator", study_validator)
builder.add_node("evaluate output", outcome_auditor)

builder.add_edge(START, "Study design")
builder.add_edge("study design", "evaluate output")
builder.add_edge("evaluate output", "analyze and plot")
builder.add_edge("analyze and plot", "studdy validator")
builder.add_edge("studdy validator", END)

graph = builder.compile()

result = graph.invoke({

})

print(result)