class MetaproteomicsAnylisisState(TypedDict): 
    data_raw_path: str #user input data
    study_plan: str | None # generated by agent 
    evaluation_study_plan: bool | None # Written by auditor, decide whether analysis should run
    downstream_analysis: bool | None # Written by analyzer, just check if it actually run
    data_outcomes: list[str] | None #written if data output 
    plot_paths:list[str] | None  #written if data output 
    issues: list[str] | None # written by all agents