"""Code-generation node.

Deterministic placeholder: no LLM call yet. It emits a fixed analysis
script so the run_code sandbox boundary can be exercised end to end.
Replace the body with a real code-generation agent later; keep the
contract (`study_plan` in, `code_text` out) the same. On a retry (after
outcome_auditor reports FAIL), `evaluator_feedback` is available for a
real agent to react to; this placeholder ignores it.
"""

from pathlib import Path

from graph.state import MetaproteomicsAnalysisState

PLACEHOLDER_CODE = '''"""Placeholder analysis script generated by the statistical_analyser stub."""
import pandas as pd

data_path = "/input/{first_input}"
df = pd.read_csv(data_path)
df.describe(include="all").to_csv("/workspace/results.csv")
print(f"Loaded {{len(df)}} rows from {{data_path}}")
'''


def statistical_analyser_node(state: MetaproteomicsAnalysisState) -> dict:
    first_input = Path(state["data_raw_paths"][0]).name
    code_text = PLACEHOLDER_CODE.format(first_input=first_input)
    return {"code_text": code_text}
