from langchain.agents import create_agent
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_ollama import ChatOllama
from graph.state import MetaproteomicsAnalysisState


#studyPlan class output structure

class StudyPlanOutput(BaseModel):
    """Validated output generated by the study-planning agent."""

    study_plan: str = Field(
        description=(
            "A detailed metaproteomics downstream-analysis plan based on "
            "the inspected dataset properties."
        )
    )

    issues: list[str] = Field(
        default_factory=list,
        description=(
            "Problems, missing information, unsupported files, or "
            "uncertainties identified while creating the plan."
        ),
    )

#Agent 

MODEL_NAME = os.getenv("OLLAMA_MODEL", "qwen2.5:7b")
OLLAMA_BASE_URL = os.getenv(
                        "OLLAMA_BASE_URL",
                        "http://localhost:11434",
                        )

model = ChatOllama(
        model=MODEL_NAME,
        base_url=OLLAMA_BASE_URL,
        temperature=0,
        )

SYSTEM_PROMPT = """
You are a study planner for metaproteomics data analysis.

Your responsibilities are:

1. Inspect the available information about the dataset.
2. Identify relevant features in the dataset, for example:
   - Number of samples
   - Number of experimental groups
   - Batch structure
   - Repeated measurements
   - Missing values
   - Available metadata
   - File formats
3.  Report any missing information or issues that prevent reliable planning.
4.  Design an appropriate downstream-analysis plan.
Do not claim to have inspected information that was not provided by the user
or returned by a tool.
"""

planner_agent = create_agent(
        model=model,
        tools=[],
        system_prompt=SYSTEM_PROMPT,
        response_format=StudyPlanOutput,
        )

#Node definition

def study_planer_node(state:MetaproteomicsAnalysisState) -> dict:
        """Simple study planner node stub. Accepts and returns a state dict."""
        
        try:
                agent_result = planner_agent.invoke(
                {
                        "messages": [
                        {
                                "role": "user",
                                "content": user_message,
                        }
                        ]
                }
                )

                #Agent modifies just the lower StudyPlanOutput class
                structured_output: StudyPlanOutput = (
                agent_result["structured_response"] 
                )

                # Return only the fields this node changes.
                return {
                "study_plan": structured_output.study_plan,
                "issues": structured_output.issues,
                }

        except Exception as exc:
                return {
                "study_plan": None,
                "issues": [
                        f"Study planner failed: {type(exc).__name__}: {exc}"
                ],
                }
      
if __name__== "__main__":
        main()