"""LangGraph node that creates a study plan with a local Ollama model."""

import json
import os

from langchain_core.messages import HumanMessage, SystemMessage
from langchain_ollama import ChatOllama
from pydantic import BaseModel, Field

from graph.state import MetaproteomicsAnalysisState
from mcp.mcp_data import inspect_csv_study


class StudyPlanOutput(BaseModel):
    """Validated output generated by the study-planning agent."""

    study_plan: str = Field(
        description="A detailed downstream metaproteomics analysis plan."
    )
    issues: list[str] = Field(
        default_factory=list,
        description="Missing information and uncertainties found while planning.",
    )


MODEL_NAME = os.getenv("OLLAMA_MODEL", "qwen2.5:7b")
OLLAMA_BASE_URL = os.getenv("OLLAMA_BASE_URL", "http://localhost:11434")

SYSTEM_PROMPT = """
You are a study planner for metaproteomics downstream data analysis. Treat all
supplied files as parts of one study. Use only the supplied inspection; do not
invent metadata or claim that a field
was inspected when it was not supplied. Distinguish rows (protein/features)
from biological samples. Explain the likely role of every file, how metadata,
abundance and annotation files should be joined, and any sample-ID mismatches.
Identify measurement level, sample/group/batch structure, missingness, and
missing metadata. Remember that missingness statistics may be preview-based.

Create a practical, ordered plan covering data validation, quality control,
filtering, transformations/normalization, exploratory analysis, statistical
testing (only when the design supports it), taxonomy/function analysis,
visualization, reproducibility, and deliverables. For a single-sample table,
explicitly avoid inferential group comparisons and propose descriptive analyses.
Put blockers and uncertainties in issues.
""".strip()


def _planner_model():
    model = ChatOllama(
        model=MODEL_NAME,
        base_url=OLLAMA_BASE_URL,
        temperature=0,
    )
    return model.with_structured_output(StudyPlanOutput, method="json_schema")


def study_planner_node(state: MetaproteomicsAnalysisState) -> dict:
    """Inspect every study CSV file and ask Ollama for a grounded study plan."""
    try:
        dataset_summary = inspect_csv_study(state["data_raw_paths"])
        user_message = (
            "Generate one integrated study plan for all files in this inspection. "
            "Account for every file explicitly:\n\n"
            + json.dumps(dataset_summary, indent=2, default=str)
        )
        structured_output = _planner_model().invoke(
            [SystemMessage(content=SYSTEM_PROMPT), HumanMessage(content=user_message)]
        )
        return {
            "study_plan": structured_output.study_plan,
            "issues": structured_output.issues,
        }
    except Exception as exc:
        return {
            "study_plan": None,
            "issues": [f"Study planner failed: {type(exc).__name__}: {exc}"],
        }


# Backward-compatible alias for the original misspelling.
study_planer_node = study_planner_node
